version: '3'
services:
  homestead:
    build: .
    restart: always
    ports:
      - "80:80" # web
      - "22:22" # ssh
    volumes:
      - ./:/apps # Project
    links:
      - mysql
      - mysql_test
  mysql:
    image: mysql
    restart: always
    expose:
      - "3306"
    environment:
      MYSQL_DATABASE: homestead
      MYSQL_USER: homestead
      MYSQL_PASSWORD: secret
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - .docker/mysql:/var/lib/mysql # database files
  mysql_test:
    image: mysql
    restart: always
    expose:
      - "3306"
    environment:
      MYSQL_DATABASE: homestead_test
      MYSQL_USER: homestead_test
      MYSQL_PASSWORD: secret
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - .docker/mysql_test:/var/lib/mysql # database files


